---
# Specific user to work with ansible
- name: Add the user 'ansadmin' for ansible tasks
  user:
    name: ansadmin
    comment: Ansible Administrator
    shell: "/bin/bash"
    create_home: yes
    state: present

# TODO :
# Create .ssh folder for the user
# Chown the .ssh folder
# Chmod 700 the ssh folder
# Create authorized_keys file with user's public key in it
# restart ssh service
# possibility to use sudo without password (/etc/sudoers > ansuser ALL=(ALL) NOPASSWD: ALL)