---
# Specific user to work with ansible
# - name: Add the user 'ansadmin' for ansible tasks
#   user:
#     name: ansadmin
#     comment: Ansible Administrator
#     groups: sudo
#     append: yes
#     create_home: no
#     state: present

# Authorize the user to connect via ssh

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts["architecture"]


- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts["lsb"]["codename"]