---
# Install dependencies needed by shell vars first
- name: Install lsb_release
  apt:
    update_cache: yes
    name: lsb-release
    state: present

# include vars AFTER having the necessary dependencies installed
- include_vars: vars/main.yml

# Cleaning of previous installs
- name: Remove previous docker installation
  apt:
    name: "{{ docker_uninstall }}"
    state: absent
    purge: yes

# Installation dependencies
- name: Install docker dependencies with a cache update before
  apt:
    update_cache: yes
    name: "{{ install_deps }}"
    state: present

# Add the repo to package manager
- name: Create a folder for keyrings if it don't exists
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download the official docker repo gpg key
  uri:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    status_code: [200,304]

- name: Install the docker's gpg key
  shell: gpg --dearmor --batch --yes -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg

- name: Set up the docker repository
  apt_repository:
    repo: deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ release }} stable
    state: present
    filename: docker

# Install docker
- name: Install docker
  apt:
    update_cache: yes
    name: "{{ docker_install }}"

# Post install configuration
- name: Create the docker group
  group:
    name: docker
    state: present

- name: add the current user in docker group
  user:
    name: "{{ current_user }}"
    groups: docker
    append: yes
    state: present