---
# update env file with variables depending on the host
- name: get the user id
  shell: id -u
  register: user_id

- name: get the group id
  shell: id -g
  register: group_id

- name: update env file with user id
  lineinfile:
    path: /app/.env
    search_string: 'USER_ID='
    line: "USER_ID={{ user_id.stdout }}"

- name: update env file with group id
  lineinfile:
    path: /app/.env
    search_string: 'GROUP_ID='
    line: "GROUP_ID={{ group_id.stdout }}"

- name: update env file with group id
  lineinfile:
    path: /app/.env
    search_string: 'DATABIND='
    line: "DATABIND={{ bind_folder }}"

- name: update env file with current host ip
  lineinfile:
    path: /app/.env
    search_string: 'WORDPRESS_SITE_URL='
    line: "WORDPRESS_SITE_URL=https://{{ ansible_host }}"
