---
# Create a directory named /app
- name: create directory /app
  file:
    path: /app
    owner: "{{ ansible_user }}"
    state: directory
  
# copy files from controler
- name: copy webapp files
  synchronize:
    src: "{{ role_path }}/files/"
    dest: "/app"
    delete: yes
  vars:
    ans_user: "{{ ansible_user }}"
  delegate_to: localhost

# copy nginx templated conf
- name: copy nginx templated conf file
  template:
    src: www.conf.j2
    dest: /app/bonus/nginx/www.conf

# copy hugo templated conf
- name: copy hugo templated conf file
  template:
    src: config.toml.j2
    dest: /app/bonus/hugo/conf/config.toml

# update user id and group id with remote server root
- name: get the user id
  shell: id -u
  register: user_id

- name: get the group id
  shell: id -g
  register: group_id

- name: update env file with user id
  lineinfile:
    path: /app/.env
    search_string: 'USER_ID='
    line: "USER_ID={{ user_id.stdout }}"

- name: update env file with group id
  lineinfile:
    path: /app/.env
    search_string: 'GROUP_ID='
    line: "GROUP_ID={{ group_id.stdout }}"

# create folders for data binding
- name: create database and wp bind folder
  become: yes
  become_user: root
  file:
    path: "{{ bind_folder }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  with_items:
    - db
    - wordpress
    - hugo

- name: update env file with group id
  lineinfile:
    path: /app/.env
    search_string: 'DATABIND='
    line: "DATABIND={{ bind_folder }}"

# update site address with current host
- name: update env file with current host ip
  lineinfile:
    path: /app/.env
    search_string: 'WORDPRESS_SITE_URL='
    line: "WORDPRESS_SITE_URL=https://{{ ansible_host }}"
